export const SET_TITLE = 'SET_TITLE';

export const GET_ISSUE_LIST = 'GET_ISSUE_LIST';
export const SET_ISSUE_LIST = 'SET_ISSUE_LIST';

export const GET_CURRENT_ISSUE = 'GET_CURRENT_ISSUE';
export const SET_CURRENT_ISSUE = 'SET_CURRENT_ISSUE';

export const SET_PAYMENT_LIST = 'SET_PAYMENT_LIST';
export const GET_PAYMENT_LIST = 'GET_PAYMENT_LIST';

export const SET_SELECTED_ISSUE = 'SET_SELECTED_ISSUE';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const ADD_ARTICLE_TO_ISSUE = 'ADD_ARTICLE_TO_ISSUE';
export const ADD_AD_TO_ISSUE = 'ADD_AD_TO_ISSUE';
export const ADD_PHOTO_TO_ISSUE = 'ADD_PHOTO_TO_ISSUE';

export const GET_CURRENT_AD = 'GET_CURRENT_AD';
export const GET_CURRENT_ARTICLE = 'GET_CURRENT_ARTICLE';
export const GET_CURRENT_PHOTO = 'GET_CURRENT_PHOTO';

export const SET_CURRENT_AD = 'GET_CURRENT_AD';
export const SET_CURRENT_ARTICLE = 'GET_CURRENT_ARTICLE';
export const SET_CURRENT_PHOTO = 'GET_CURRENT_PHOTO';

export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const UPDATE_PHOTO_WITH_IMAGE = 'UPDATE_PHOTO_WITH_IMAGE';
export const UPDATE_PHOTO_WITH_ID = 'UPDATE_PHOTO_WITH_ID';
export const SET_PHOTOS = 'SET_PHOTOS';
export const SET_PHOTO_SIZE = 'SET_PHOTO_SIZE';

export const UPDATE_AD_WITH_ID = 'UPDATE_AD_WITH_ID';
export const SET_ADS = 'SET_ADS';
export const SET_AD_PLACEMENT = 'SET_AD_PLACEMENT';

export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLE_TITLE = 'SET_ARTICLE_TITLE';
export const SET_ARTICLE_CONTENT = 'SET_ARTICLE_CONTENT';
export const UPDATE_ARTICLE_WITH_ID = 'UPDATE_ARTICLE_WITH_ID';

export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const API_ERROR = 'API_ERROR';
